% January, 2017
% script for post-processing for test 7 - PRO
clear all; clc;
load('output\test7_pro_results.mat');
func=@(x)exp(x); % attention
% errors

j=1;
for i=1:numel(degree)
    for f=1:numel(flux_num)
        for k=1:numel(num_cells)
            error{i}(k,f)=max(abs(pro{i}{k,f}.u_approx'-m{k}.eval_mean_value_cells(func)));
            j=j+1;
        end
    end
end
P1_PRO1=format_errors_orders(error{1}(:,1),numel(num_cells),num_cells);
P1_PRO2=format_errors_orders(error{1}(:,2),numel(num_cells),num_cells);
P2_PRO1=format_errors_orders(error{2}(:,1),numel(num_cells),num_cells);
P2_PRO2=format_errors_orders(error{2}(:,2),numel(num_cells),num_cells);
P3_PRO1=format_errors_orders(error{3}(:,1),numel(num_cells),num_cells);
P3_PRO2=format_errors_orders(error{3}(:,2),numel(num_cells),num_cells);
P4_PRO1=format_errors_orders(error{4}(:,1),numel(num_cells),num_cells);
P4_PRO2=format_errors_orders(error{4}(:,2),numel(num_cells),num_cells);
P5_PRO1=format_errors_orders(error{5}(:,1),numel(num_cells),num_cells);
P5_PRO2=format_errors_orders(error{5}(:,2),numel(num_cells),num_cells);

% write tables
label='Table:PRO:Rodrigo:Test7';
% directory1='..\..\..\..\..\Report\BIC_2017_report\tables\new_pro_tables\test1.tex';
directory2='output\test7.tex';
caption='$n_1=n_2=d$, $n_3=d+1$, $\omega=1|1$ (minimum size).';

% mfvl_write_table3(directory1,caption,...
%     label,num_cells,degree,...
%     P1_PRO1.e,P1_PRO1.o,...
%     P1_PRO2.e,P1_PRO2.o,...
%     P2_PRO1.e,P2_PRO1.o,...
%     P2_PRO2.e,P2_PRO2.o,...
%     P3_PRO1.e,P3_PRO1.o,...
%     P3_PRO2.e,P3_PRO2.o,...
%     P4_PRO1.e,P4_PRO1.o,...
%     P4_PRO2.e,P4_PRO2.o,...
%     P5_PRO1.e,P5_PRO1.o,...
%     P5_PRO2.e,P5_PRO2.o);

mfvl_write_table3(directory2,caption,...
    label,num_cells,degree,...
    P1_PRO1.e,P1_PRO1.o,...
    P1_PRO2.e,P1_PRO2.o,...
    P2_PRO1.e,P2_PRO1.o,...
    P2_PRO2.e,P2_PRO2.o,...
    P3_PRO1.e,P3_PRO1.o,...
    P3_PRO2.e,P3_PRO2.o,...
    P4_PRO1.e,P4_PRO1.o,...
    P4_PRO2.e,P4_PRO2.o,...
    P5_PRO1.e,P5_PRO1.o,...
    P5_PRO2.e,P5_PRO2.o);