% January, 2017
% script for post-processing for test 6 - PRO
clear all; clc;
load('output/requisites.mat');
func=@(x)exp(x); % attention
% errors
j=1;
for i=1:numel(degree)
    for f=1:numel(flux_num)
        if (flux_num(f)==1)
            flux='pro1';
        else
            flux='pro2';
        end
        for k=1:numel(num_cells)
            file_name=['nc' num2str(num_cells(k)) '_deg' num2str(degree(i)) '_wei1' num2str(weight1) num2str(weight2) '_' flux];
            sol=importdata(['output/' file_name '/sol.dat']);
            load(['output/' file_name '/mesh.mat']);
            
            error{i}(k,f)=max(abs(sol'-mesh.eval_mean_value_cells(func)));
	    j=j+1;
        end
    end
end
P1_PRO1=format_errors_orders(error{1}(:,1),numel(num_cells),num_cells);
P1_PRO2=format_errors_orders(error{1}(:,2),numel(num_cells),num_cells);
P2_PRO1=format_errors_orders(error{2}(:,1),numel(num_cells),num_cells);
P2_PRO2=format_errors_orders(error{2}(:,2),numel(num_cells),num_cells);
P3_PRO1=format_errors_orders(error{3}(:,1),numel(num_cells),num_cells);
P3_PRO2=format_errors_orders(error{3}(:,2),numel(num_cells),num_cells);
P4_PRO1=format_errors_orders(error{4}(:,1),numel(num_cells),num_cells);
P4_PRO2=format_errors_orders(error{4}(:,2),numel(num_cells),num_cells);
P5_PRO1=format_errors_orders(error{5}(:,1),numel(num_cells),num_cells);
P5_PRO2=format_errors_orders(error{5}(:,2),numel(num_cells),num_cells);

if ~exist('output/tables', 'dir')
    mkdir('output/tables');
end
% write tables
label='Table:PRO:Test6';
directory1='../../../../../Report/BIC_2017_report/tables/new_pro_tables/test6.tex';
directory2='output/tables/test6.tex';
caption='Numerical results of PRO1 and PRO2 schemes for $/phi(x)=/exp(x)$, $/kappa(x)=x+1$, and $u(x)=0$.';

% mfvl_write_table3(directory1,caption,...
%     label,num_cells,degree,...
%     P1_PRO1.e,P1_PRO1.o,...
%     P1_PRO2.e,P1_PRO2.o,...
%     P2_PRO1.e,P2_PRO1.o,...
%     P2_PRO2.e,P2_PRO2.o,...
%     P3_PRO1.e,P3_PRO1.o,...
%     P3_PRO2.e,P3_PRO2.o,...
%     P4_PRO1.e,P4_PRO1.o,...
%     P4_PRO2.e,P4_PRO2.o,...
%     P5_PRO1.e,P5_PRO1.o,...
%     P5_PRO2.e,P5_PRO2.o);

mfvl_write_table3(directory2,caption,...
    label,num_cells,degree,...
    P1_PRO1.e,P1_PRO1.o,...
    P1_PRO2.e,P1_PRO2.o,...
    P2_PRO1.e,P2_PRO1.o,...
    P2_PRO2.e,P2_PRO2.o,...
    P3_PRO1.e,P3_PRO1.o,...
    P3_PRO2.e,P3_PRO2.o,...
    P4_PRO1.e,P4_PRO1.o,...
    P4_PRO2.e,P4_PRO2.o,...
    P5_PRO1.e,P5_PRO1.o,...
    P5_PRO2.e,P5_PRO2.o);
